# Generated by Django 5.1.2 on 2024-10-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_itemestoque_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='item_pedido',
            new_name='item_estoque',
        ),
    ]
